version: "3.9"
services:
  shared:
    image: "busybox"
    volumes:
      - db:/var/lib/postgresql/data:cached
      - bundle:/usr/local/bundle:cached
      - node_modules:/app/node_modules
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes_from:
      - shared
    ports:
      - 5432:5432

  api: &app_base
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./.env.dev
    volumes:
      - .:/app:cached
    volumes_from:
      - shared
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  db:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local
