#!/usr/bin/env bash

cp .env.dev.sample .env.dev

docker-compose build
docker-compose run web rails new . --api --force --no-deps --database=postgresql

cp -f template/database.yml config/database.yml
cp -f template/package.json ./package.json
docker-compose run --rm rails yarn install --check-files
echo "

group :development do
  gem 'rubocop', require: false
  gem 'solargraph'
  gem 'pry-byebug'
  gem 'pry-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
end

" >> Gemfile
docker-compose run --rm rails bundle install
