#!/usr/bin/env bash

cp .env.dev.sample .env.dev

docker-compose build
docker-compose run rails rails new . --api --force --no-deps --database=postgresql --skip-git

cp -f template/database.yml config/database.yml
echo "

group :development do
  gem 'rubocop', require: false
  gem 'pry-byebug'
  gem 'pry-rails'
end

" >> Gemfile
docker-compose run --rm rails bundle install
